services:
  ppsrfileupload.server:
    image: ${DOCKER_REGISTRY-}ppsrfileuploadserver
    build:
      context: .
      dockerfile: PPSRFileUpload.Server/Dockerfile
    ports:
      - 8081:8081
      - 8080:8080
    depends_on:
      - sql_sqlserver
  sql_sqlserver:
    container_name: sql_sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=PPSRImport@100
    ports:
      - "1433:1433" 
  fileupload-frontend:
   image: fileupload-frontend
   working_dir: /app
   build:
      context: ppsrfileupload.client
      dockerfile: Docker
   environment:
     PORT: 3000
     PROXY_API: PPSRFileUpload.Server:8081/
   ports:
     - 3000:3000